FROM node:22-alpine
WORKDIR /app

RUN corepack enable pnpm

# 1. Copiamos los archivos de dependencias primero para cachear la capa
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm config set registry https://registry.npmmirror.com/

# 2. Instalamos dependencias
RUN npm_config_network_timeout=600000 pnpm install --frozen-lockfile --ignore-scripts

# 3. Copiamos el resto del código (ahora asumiendo que haces el build DENTRO de la carpeta amm_indexer)
COPY . .

# 4. Generamos los clientes de Prisma
RUN pnpm run prisma:generate:sqlite
RUN pnpm run prisma:generate:supabase

# 5. Ejecutamos el indexador
CMD ["npx", "tsx", "scripts/run-indexer.ts"]
