/**
 * One-time, idempotent migration: V1 (Token/Pair/GroupConfiguration) -> V2
 * (tokens_v2/ammpair_v2/group_configuration) on the agjq... Supabase.
 *
 * Additive & safe: does NOT drop or modify V1 tables. Safe to re-run.
 * Run: npx tsx scripts/migrate-v2.ts
 */
import { Client } from 'pg';
import * as dotenv from 'dotenv';
dotenv.config();

function projectRef(): string {
  const m = (process.env.DATABASE_URL || '').match(/postgres\.([a-z0-9]+)[:@]/);
  return m ? m[1] : 'UNKNOWN';
}

const EXPECTED_REF = 'agjqkuhdbxhjvnqbsqwy';

async function counts(c: Client) {
  const out: Record<string, number | string> = {};
  for (const n of ['Token', 'Pair', 'GroupConfiguration', 'tokens_v2', 'ammpair_v2', 'group_configuration']) {
    try {
      const r = await c.query(`SELECT COUNT(*)::int AS n FROM "${n}"`);
      out[n] = r.rows[0].n;
    } catch (e: any) {
      out[n] = `ERR(${e.message})`;
    }
  }
  return out;
}

async function main() {
  const ref = projectRef();
  console.log('PROJECT REF =', ref);
  if (ref !== EXPECTED_REF) {
    throw new Error(`ABORT: expected ref ${EXPECTED_REF} but got ${ref}. Wrong Supabase!`);
  }

  const c = new Client({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });
  await c.connect();

  console.log('BEFORE:', JSON.stringify(await counts(c)));

  await c.query('BEGIN');
  try {
    // 1) Extend tokens_v2 with the fields the bot needs (supply) + numId (short, Telegram callback) + createdAt
    await c.query(`
      ALTER TABLE tokens_v2
        ADD COLUMN IF NOT EXISTS "numId" BIGINT GENERATED BY DEFAULT AS IDENTITY,
        ADD COLUMN IF NOT EXISTS "wrappedAddress" text,
        ADD COLUMN IF NOT EXISTS "maxSupply" bigint,
        ADD COLUMN IF NOT EXISTS "circulatingSupply" bigint,
        ADD COLUMN IF NOT EXISTS "minTradeVolume" numeric,
        ADD COLUMN IF NOT EXISTS "createdAt" timestamp without time zone DEFAULT now()
    `);
    await c.query(`
      DO $$ BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'tokens_v2_numId_key'
        ) THEN
          ALTER TABLE tokens_v2 ADD CONSTRAINT "tokens_v2_numId_key" UNIQUE ("numId");
        END IF;
      END $$;
    `);
    await c.query(`CREATE INDEX IF NOT EXISTS "tokens_v2_network_symbol_idx" ON tokens_v2 (network, symbol)`);

    // 2) ammpair_v2
    await c.query(`
      CREATE TABLE IF NOT EXISTS ammpair_v2 (
        id text PRIMARY KEY,
        pair text NOT NULL,
        network text NOT NULL,
        creator text NOT NULL,
        "token0Address" text NOT NULL REFERENCES tokens_v2(id),
        "token1Address" text NOT NULL REFERENCES tokens_v2(id),
        "lpFeePercent" numeric(10,4) NOT NULL,
        verified boolean NOT NULL DEFAULT false,
        "displayOrder" integer NOT NULL DEFAULT 0,
        "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
        CONSTRAINT ammpair_v2_pair_network_key UNIQUE (pair, network)
      )
    `);

    // 3) Migrate Token -> tokens_v2 (preserve old numeric id in numId for callback compatibility)
    const tok = await c.query(`
      INSERT INTO tokens_v2 (id, network, name, symbol, decimals, "wrappedAddress", "maxSupply", "circulatingSupply", "minTradeVolume", "createdAt", "numId")
      SELECT address, network, name, symbol, decimals, "wrappedAddress", "maxSupply", "circulatingSupply", "minTradeVolume", "createdAt", id
      FROM "Token"
      ON CONFLICT (id) DO NOTHING
    `);
    console.log('inserted tokens_v2 rows:', tok.rowCount);

    // keep identity sequence above the largest migrated numId
    await c.query(`
      SELECT setval(
        pg_get_serial_sequence('tokens_v2', 'numId'),
        COALESCE((SELECT MAX("numId") FROM tokens_v2), 0) + 1,
        false
      )
    `);

    // 4) Migrate Pair -> ammpair_v2 (only rows that actually have a pool address)
    const pr = await c.query(`
      INSERT INTO ammpair_v2 (id, pair, network, creator, "token0Address", "token1Address", "lpFeePercent", "createdAt")
      SELECT p."spikeyAmmPairAddress", p."spikeyAmmPairAddress", p.network, 'migrated_v1',
             t0.address, t1.address, '0.003', p."createdAt"
      FROM "Pair" p
      JOIN "Token" t0 ON t0.id = p."token0Id"
      JOIN "Token" t1 ON t1.id = p."token1Id"
      WHERE p."spikeyAmmPairAddress" IS NOT NULL
      ON CONFLICT (id) DO NOTHING
    `);
    console.log('inserted ammpair_v2 rows:', pr.rowCount);

    // 5) Migrate GroupConfiguration -> group_configuration (Int token id -> token address)
    const gc = await c.query(`
      INSERT INTO group_configuration
        ("chatId","spikeMonitorEnabled","spikeMonitorTokenId","spikeMonitorThreadId","spikeMonitorGifUrl","spikeMonitorTimeframe","spikeMonitorInterval")
      SELECT g."chatId", g."spikeMonitorEnabled",
             (SELECT t.address FROM "Token" t WHERE t.id = g."spikeMonitorTokenId"),
             g."spikeMonitorThreadId", g."spikeMonitorGifUrl", g."spikeMonitorTimeframe", g."spikeMonitorInterval"
      FROM "GroupConfiguration" g
      ON CONFLICT ("chatId") DO NOTHING
    `);
    console.log('inserted group_configuration rows:', gc.rowCount);

    await c.query('COMMIT');
  } catch (e) {
    await c.query('ROLLBACK');
    throw e;
  }

  console.log('AFTER:', JSON.stringify(await counts(c)));

  // sanity
  const gcBad = await c.query(
    `SELECT COUNT(*)::int AS n FROM group_configuration WHERE "spikeMonitorTokenId" IS NOT NULL
       AND "spikeMonitorTokenId" NOT IN (SELECT id FROM tokens_v2)`
  );
  console.log('group_configuration rows with dangling token FK:', gcBad.rows[0].n);

  await c.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
